import { MigrationInterface, QueryRunner } from 'typeorm';

export class initDatabase1650418037986 implements MigrationInterface {

  name = 'initDatabase1650418037986'

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`CREATE TABLE \`access_token\` (\`id\` int NOT NULL AUTO_INCREMENT, \`token\` varchar(255) NOT NULL, \`expirationDate\` datetime NOT NULL, \`userId\` int NULL, UNIQUE INDEX \`REL_9949557d0e1b2c19e5344c171e\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`bank\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`image\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`bank_account\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`accountNumber\` varchar(255) NOT NULL, \`bankId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`business_user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`userName\` varchar(255) NOT NULL, \`password\` varchar(255) NULL, \`state\` enum ('ACTIVATED', 'NOT_ACTIVATED', 'DISABLED') NOT NULL DEFAULT 'NOT_ACTIVATED', \`deletedAt\` datetime(6) NULL, \`userId\` int NULL, \`businessId\` int NULL, UNIQUE INDEX \`IDX_f1f2813cda8ccf542ae045cc2d\` (\`userName\`), UNIQUE INDEX \`IDX_2a95f576e13701ee12c7e502c4\` (\`password\`), UNIQUE INDEX \`REL_51d41bcadff576b7477d729d56\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`sales_report\` (\`id\` int NOT NULL AUTO_INCREMENT, \`date\` datetime NOT NULL, \`sales\` decimal(10,2) NOT NULL DEFAULT '0.00', \`balance\` decimal(10,2) NOT NULL DEFAULT '0.00', \`profit\` decimal(10,2) NOT NULL DEFAULT '0.00', \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`business_sales_report\` (\`id\` int NOT NULL AUTO_INCREMENT, \`businessId\` int NULL, \`businessUserId\` int NULL, \`salesReportId\` int NULL, UNIQUE INDEX \`REL_ffad1a9aba53f8773fad14e2a3\` (\`salesReportId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`customer\` (\`id\` int NOT NULL AUTO_INCREMENT, \`docNumber\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`password\` varchar(255) NULL, \`userId\` int NULL, UNIQUE INDEX \`IDX_47bd75ef7644513e402222cef7\` (\`docNumber\`), UNIQUE INDEX \`IDX_fdb2f3ad8115da4c7718109a6e\` (\`email\`), UNIQUE INDEX \`IDX_6c497e212bc2ac2329cb4c059d\` (\`password\`), UNIQUE INDEX \`REL_3f62b42ed23958b120c235f74d\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`business\` (\`id\` int NOT NULL AUTO_INCREMENT, \`rnc\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`phone\` varchar(255) NOT NULL, \`email\` varchar(255) NULL, \`city\` varchar(255) NOT NULL, \`address\` varchar(255) NOT NULL, \`system\` enum ('WEB_APP', 'MOBILE_APP') NOT NULL, \`percent\` decimal(10,2) NOT NULL DEFAULT '0.00', \`userId\` int NULL, \`customerId\` int NULL, UNIQUE INDEX \`IDX_8b486b91e43537c87c4266053f\` (\`rnc\`), UNIQUE INDEX \`IDX_4cca40c3813d4b88a83edb459b\` (\`email\`), UNIQUE INDEX \`REL_ac8ad696f6731c86b52c058c0c\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`withdrawal\` (\`id\` int NOT NULL AUTO_INCREMENT, \`date\` datetime NOT NULL, \`description\` varchar(255) NOT NULL, \`balanceId\` int NULL, \`bankAccountId\` int NULL, UNIQUE INDEX \`REL_50b0ddcfcf9e6549a609871e4c\` (\`balanceId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`system_sales_report\` (\`id\` int NOT NULL AUTO_INCREMENT, \`date\` datetime NOT NULL, \`withdrawalId\` int NULL, UNIQUE INDEX \`REL_bb8b304d39fbc764dcfc3ce500\` (\`withdrawalId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`provider_sales_report\` (\`id\` int NOT NULL AUTO_INCREMENT, \`salesReportId\` int NULL, \`providerId\` int NULL, \`systemSalesReportId\` int NULL, UNIQUE INDEX \`REL_0bdb740373bf2700155a0465f0\` (\`salesReportId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`provider\` (\`id\` int NOT NULL, \`rnc\` varchar(255) NULL, \`name\` varchar(255) NOT NULL, \`image\` varchar(255) NOT NULL, \`phone\` varchar(255) NULL, \`email\` varchar(255) NULL, \`enabled\` tinyint NOT NULL DEFAULT 1, \`userId\` int NULL, UNIQUE INDEX \`REL_da1c78142007c621b5498c818c\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`provider_product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`key\` varchar(255) NOT NULL, \`percent\` decimal(10,2) NOT NULL DEFAULT '0.00', \`deletedAt\` datetime(6) NULL, \`providerId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`product\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`type\` enum ('Recarga', 'Paquetico') NOT NULL, \`image\` varchar(255) NOT NULL, \`percent\` decimal(10,2) NOT NULL DEFAULT '0.00', \`min\` decimal(10,2) NOT NULL DEFAULT '0.00', \`max\` decimal(10,2) NOT NULL DEFAULT '0.00', \`enabled\` tinyint NOT NULL DEFAULT 1, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`transaction\` (\`id\` int NOT NULL AUTO_INCREMENT, \`phone\` varchar(255) NOT NULL, \`amount\` int NOT NULL, \`date\` datetime NOT NULL, \`reference\` varchar(255) NOT NULL, \`businessId\` int NULL, \`businessUserId\` int NULL, \`providerId\` int NULL, \`productId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`profit\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`date\` datetime NOT NULL, \`transactionId\` int NULL, \`userId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`permission\` (\`id\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`role_permission\` (\`id\` int NOT NULL AUTO_INCREMENT, \`roleId\` varchar(255) NULL, \`permissionId\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`role\` (\`id\` varchar(255) NOT NULL, \`name\` varchar(255) NOT NULL, UNIQUE INDEX \`IDX_ae4578dcaed5adff96595e6166\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`roleId\` varchar(255) NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`admin\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`email\` varchar(255) NOT NULL, \`password\` varchar(255) NOT NULL, \`userId\` int NULL, UNIQUE INDEX \`IDX_de87485f6489f5d0995f584195\` (\`email\`), UNIQUE INDEX \`IDX_407c6798fe20fd5d75de4a233c\` (\`password\`), UNIQUE INDEX \`REL_f8a889c4362d78f056960ca6da\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`deposit\` (\`id\` int NOT NULL AUTO_INCREMENT, \`reference\` varchar(255) NOT NULL, \`date\` datetime NOT NULL, \`bankAccountId\` int NULL, \`userId\` int NULL, \`assignedById\` int NULL, \`balanceId\` int NULL, UNIQUE INDEX \`REL_4cdb0ed9cc37864f759ced1fc4\` (\`balanceId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`balance\` (\`id\` int NOT NULL AUTO_INCREMENT, \`amount\` decimal(10,2) NOT NULL DEFAULT '0.00', \`date\` datetime NOT NULL, \`userId\` int NULL, \`transactionId\` int NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`session\` (\`id\` varchar(255) NOT NULL, \`data\` json NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`question\` (\`id\` int NOT NULL AUTO_INCREMENT, \`name\` varchar(255) NOT NULL, \`contact\` varchar(255) NOT NULL, \`question\` varchar(255) NOT NULL, PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`CREATE TABLE \`system_user\` (\`id\` int NOT NULL AUTO_INCREMENT, \`userId\` int NULL, UNIQUE INDEX \`REL_278b00602420bd2b1dbcb70ee5\` (\`userId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
    await queryRunner.query(`ALTER TABLE \`access_token\` ADD CONSTRAINT \`FK_9949557d0e1b2c19e5344c171e9\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`bank_account\` ADD CONSTRAINT \`FK_57fe4146ab12f9f7d581a42962f\` FOREIGN KEY (\`bankId\`) REFERENCES \`bank\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`bank_account\` ADD CONSTRAINT \`FK_c2ba1381682b0291238cbc7a65d\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`business_user\` ADD CONSTRAINT \`FK_51d41bcadff576b7477d729d56d\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`business_user\` ADD CONSTRAINT \`FK_e76c2c1862017882a0d81c6f455\` FOREIGN KEY (\`businessId\`) REFERENCES \`business\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`sales_report\` ADD CONSTRAINT \`FK_d2e47378eeff6f419a25ce613ff\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`business_sales_report\` ADD CONSTRAINT \`FK_66b1afea7ca3ca8565194685267\` FOREIGN KEY (\`businessId\`) REFERENCES \`business\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`business_sales_report\` ADD CONSTRAINT \`FK_1765fee3f95960173b2b82d72d8\` FOREIGN KEY (\`businessUserId\`) REFERENCES \`business_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`business_sales_report\` ADD CONSTRAINT \`FK_ffad1a9aba53f8773fad14e2a37\` FOREIGN KEY (\`salesReportId\`) REFERENCES \`sales_report\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`customer\` ADD CONSTRAINT \`FK_3f62b42ed23958b120c235f74df\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_ac8ad696f6731c86b52c058c0c6\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`business\` ADD CONSTRAINT \`FK_e06a6c379ba0a3531a82cb27e56\` FOREIGN KEY (\`customerId\`) REFERENCES \`customer\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`withdrawal\` ADD CONSTRAINT \`FK_50b0ddcfcf9e6549a609871e4c1\` FOREIGN KEY (\`balanceId\`) REFERENCES \`balance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`withdrawal\` ADD CONSTRAINT \`FK_bd62aebedfd3cae473c41d2b458\` FOREIGN KEY (\`bankAccountId\`) REFERENCES \`bank_account\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`system_sales_report\` ADD CONSTRAINT \`FK_bb8b304d39fbc764dcfc3ce5000\` FOREIGN KEY (\`withdrawalId\`) REFERENCES \`withdrawal\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`provider_sales_report\` ADD CONSTRAINT \`FK_0bdb740373bf2700155a0465f04\` FOREIGN KEY (\`salesReportId\`) REFERENCES \`sales_report\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`provider_sales_report\` ADD CONSTRAINT \`FK_694ecf8b78627258ceca83e37d3\` FOREIGN KEY (\`providerId\`) REFERENCES \`provider\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`provider_sales_report\` ADD CONSTRAINT \`FK_70ef060c6a874fc96cb66314ceb\` FOREIGN KEY (\`systemSalesReportId\`) REFERENCES \`system_sales_report\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`provider\` ADD CONSTRAINT \`FK_da1c78142007c621b5498c818c1\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`provider_product\` ADD CONSTRAINT \`FK_13262e3b843ed76fe9c2ee59ef0\` FOREIGN KEY (\`providerId\`) REFERENCES \`provider\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`provider_product\` ADD CONSTRAINT \`FK_275efbbfce34a9ee58a66ff84e6\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_ebb97cc6ceb335b0d507fe147cf\` FOREIGN KEY (\`businessId\`) REFERENCES \`business\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_eead88eabcbc96d28162db85aa6\` FOREIGN KEY (\`businessUserId\`) REFERENCES \`business_user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_e2fa3946721d92813dee94c8f5f\` FOREIGN KEY (\`providerId\`) REFERENCES \`provider\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`transaction\` ADD CONSTRAINT \`FK_fd965536176f304a7dd64937165\` FOREIGN KEY (\`productId\`) REFERENCES \`product\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`profit\` ADD CONSTRAINT \`FK_c4ea09fa80fc05ef0f812bc0913\` FOREIGN KEY (\`transactionId\`) REFERENCES \`transaction\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`profit\` ADD CONSTRAINT \`FK_1dd0beb772d6e36ea4c55f96b91\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`role_permission\` ADD CONSTRAINT \`FK_e3130a39c1e4a740d044e685730\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`role_permission\` ADD CONSTRAINT \`FK_72e80be86cab0e93e67ed1a7a9a\` FOREIGN KEY (\`permissionId\`) REFERENCES \`permission\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`user\` ADD CONSTRAINT \`FK_c28e52f758e7bbc53828db92194\` FOREIGN KEY (\`roleId\`) REFERENCES \`role\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`admin\` ADD CONSTRAINT \`FK_f8a889c4362d78f056960ca6dad\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`deposit\` ADD CONSTRAINT \`FK_a7e68ff381a65ad9eb2d77b5d53\` FOREIGN KEY (\`bankAccountId\`) REFERENCES \`bank_account\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`deposit\` ADD CONSTRAINT \`FK_b3f1383d11c01f2b6e63c37575b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`deposit\` ADD CONSTRAINT \`FK_3269c94a31c231efb6e19801968\` FOREIGN KEY (\`assignedById\`) REFERENCES \`admin\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`deposit\` ADD CONSTRAINT \`FK_4cdb0ed9cc37864f759ced1fc46\` FOREIGN KEY (\`balanceId\`) REFERENCES \`balance\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`balance\` ADD CONSTRAINT \`FK_9297a70b26dc787156fa49de26b\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`balance\` ADD CONSTRAINT \`FK_2d65545655da4dabfe0136afaf4\` FOREIGN KEY (\`transactionId\`) REFERENCES \`transaction\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    await queryRunner.query(`ALTER TABLE \`system_user\` ADD CONSTRAINT \`FK_278b00602420bd2b1dbcb70ee59\` FOREIGN KEY (\`userId\`) REFERENCES \`user\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`system_user\` DROP FOREIGN KEY \`FK_278b00602420bd2b1dbcb70ee59\``);
    await queryRunner.query(`ALTER TABLE \`balance\` DROP FOREIGN KEY \`FK_2d65545655da4dabfe0136afaf4\``);
    await queryRunner.query(`ALTER TABLE \`balance\` DROP FOREIGN KEY \`FK_9297a70b26dc787156fa49de26b\``);
    await queryRunner.query(`ALTER TABLE \`deposit\` DROP FOREIGN KEY \`FK_4cdb0ed9cc37864f759ced1fc46\``);
    await queryRunner.query(`ALTER TABLE \`deposit\` DROP FOREIGN KEY \`FK_3269c94a31c231efb6e19801968\``);
    await queryRunner.query(`ALTER TABLE \`deposit\` DROP FOREIGN KEY \`FK_b3f1383d11c01f2b6e63c37575b\``);
    await queryRunner.query(`ALTER TABLE \`deposit\` DROP FOREIGN KEY \`FK_a7e68ff381a65ad9eb2d77b5d53\``);
    await queryRunner.query(`ALTER TABLE \`admin\` DROP FOREIGN KEY \`FK_f8a889c4362d78f056960ca6dad\``);
    await queryRunner.query(`ALTER TABLE \`user\` DROP FOREIGN KEY \`FK_c28e52f758e7bbc53828db92194\``);
    await queryRunner.query(`ALTER TABLE \`role_permission\` DROP FOREIGN KEY \`FK_72e80be86cab0e93e67ed1a7a9a\``);
    await queryRunner.query(`ALTER TABLE \`role_permission\` DROP FOREIGN KEY \`FK_e3130a39c1e4a740d044e685730\``);
    await queryRunner.query(`ALTER TABLE \`profit\` DROP FOREIGN KEY \`FK_1dd0beb772d6e36ea4c55f96b91\``);
    await queryRunner.query(`ALTER TABLE \`profit\` DROP FOREIGN KEY \`FK_c4ea09fa80fc05ef0f812bc0913\``);
    await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_fd965536176f304a7dd64937165\``);
    await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_e2fa3946721d92813dee94c8f5f\``);
    await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_eead88eabcbc96d28162db85aa6\``);
    await queryRunner.query(`ALTER TABLE \`transaction\` DROP FOREIGN KEY \`FK_ebb97cc6ceb335b0d507fe147cf\``);
    await queryRunner.query(`ALTER TABLE \`provider_product\` DROP FOREIGN KEY \`FK_275efbbfce34a9ee58a66ff84e6\``);
    await queryRunner.query(`ALTER TABLE \`provider_product\` DROP FOREIGN KEY \`FK_13262e3b843ed76fe9c2ee59ef0\``);
    await queryRunner.query(`ALTER TABLE \`provider\` DROP FOREIGN KEY \`FK_da1c78142007c621b5498c818c1\``);
    await queryRunner.query(`ALTER TABLE \`provider_sales_report\` DROP FOREIGN KEY \`FK_70ef060c6a874fc96cb66314ceb\``);
    await queryRunner.query(`ALTER TABLE \`provider_sales_report\` DROP FOREIGN KEY \`FK_694ecf8b78627258ceca83e37d3\``);
    await queryRunner.query(`ALTER TABLE \`provider_sales_report\` DROP FOREIGN KEY \`FK_0bdb740373bf2700155a0465f04\``);
    await queryRunner.query(`ALTER TABLE \`system_sales_report\` DROP FOREIGN KEY \`FK_bb8b304d39fbc764dcfc3ce5000\``);
    await queryRunner.query(`ALTER TABLE \`withdrawal\` DROP FOREIGN KEY \`FK_bd62aebedfd3cae473c41d2b458\``);
    await queryRunner.query(`ALTER TABLE \`withdrawal\` DROP FOREIGN KEY \`FK_50b0ddcfcf9e6549a609871e4c1\``);
    await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_e06a6c379ba0a3531a82cb27e56\``);
    await queryRunner.query(`ALTER TABLE \`business\` DROP FOREIGN KEY \`FK_ac8ad696f6731c86b52c058c0c6\``);
    await queryRunner.query(`ALTER TABLE \`customer\` DROP FOREIGN KEY \`FK_3f62b42ed23958b120c235f74df\``);
    await queryRunner.query(`ALTER TABLE \`business_sales_report\` DROP FOREIGN KEY \`FK_ffad1a9aba53f8773fad14e2a37\``);
    await queryRunner.query(`ALTER TABLE \`business_sales_report\` DROP FOREIGN KEY \`FK_1765fee3f95960173b2b82d72d8\``);
    await queryRunner.query(`ALTER TABLE \`business_sales_report\` DROP FOREIGN KEY \`FK_66b1afea7ca3ca8565194685267\``);
    await queryRunner.query(`ALTER TABLE \`sales_report\` DROP FOREIGN KEY \`FK_d2e47378eeff6f419a25ce613ff\``);
    await queryRunner.query(`ALTER TABLE \`business_user\` DROP FOREIGN KEY \`FK_e76c2c1862017882a0d81c6f455\``);
    await queryRunner.query(`ALTER TABLE \`business_user\` DROP FOREIGN KEY \`FK_51d41bcadff576b7477d729d56d\``);
    await queryRunner.query(`ALTER TABLE \`bank_account\` DROP FOREIGN KEY \`FK_c2ba1381682b0291238cbc7a65d\``);
    await queryRunner.query(`ALTER TABLE \`bank_account\` DROP FOREIGN KEY \`FK_57fe4146ab12f9f7d581a42962f\``);
    await queryRunner.query(`ALTER TABLE \`access_token\` DROP FOREIGN KEY \`FK_9949557d0e1b2c19e5344c171e9\``);
    await queryRunner.query(`DROP INDEX \`REL_278b00602420bd2b1dbcb70ee5\` ON \`system_user\``);
    await queryRunner.query(`DROP TABLE \`system_user\``);
    await queryRunner.query(`DROP TABLE \`question\``);
    await queryRunner.query(`DROP TABLE \`session\``);
    await queryRunner.query(`DROP TABLE \`balance\``);
    await queryRunner.query(`DROP INDEX \`REL_4cdb0ed9cc37864f759ced1fc4\` ON \`deposit\``);
    await queryRunner.query(`DROP TABLE \`deposit\``);
    await queryRunner.query(`DROP INDEX \`REL_f8a889c4362d78f056960ca6da\` ON \`admin\``);
    await queryRunner.query(`DROP INDEX \`IDX_407c6798fe20fd5d75de4a233c\` ON \`admin\``);
    await queryRunner.query(`DROP INDEX \`IDX_de87485f6489f5d0995f584195\` ON \`admin\``);
    await queryRunner.query(`DROP TABLE \`admin\``);
    await queryRunner.query(`DROP TABLE \`user\``);
    await queryRunner.query(`DROP INDEX \`IDX_ae4578dcaed5adff96595e6166\` ON \`role\``);
    await queryRunner.query(`DROP TABLE \`role\``);
    await queryRunner.query(`DROP TABLE \`role_permission\``);
    await queryRunner.query(`DROP TABLE \`permission\``);
    await queryRunner.query(`DROP TABLE \`profit\``);
    await queryRunner.query(`DROP TABLE \`transaction\``);
    await queryRunner.query(`DROP TABLE \`product\``);
    await queryRunner.query(`DROP TABLE \`provider_product\``);
    await queryRunner.query(`DROP INDEX \`REL_da1c78142007c621b5498c818c\` ON \`provider\``);
    await queryRunner.query(`DROP TABLE \`provider\``);
    await queryRunner.query(`DROP INDEX \`REL_0bdb740373bf2700155a0465f0\` ON \`provider_sales_report\``);
    await queryRunner.query(`DROP TABLE \`provider_sales_report\``);
    await queryRunner.query(`DROP INDEX \`REL_bb8b304d39fbc764dcfc3ce500\` ON \`system_sales_report\``);
    await queryRunner.query(`DROP TABLE \`system_sales_report\``);
    await queryRunner.query(`DROP INDEX \`REL_50b0ddcfcf9e6549a609871e4c\` ON \`withdrawal\``);
    await queryRunner.query(`DROP TABLE \`withdrawal\``);
    await queryRunner.query(`DROP INDEX \`REL_ac8ad696f6731c86b52c058c0c\` ON \`business\``);
    await queryRunner.query(`DROP INDEX \`IDX_4cca40c3813d4b88a83edb459b\` ON \`business\``);
    await queryRunner.query(`DROP INDEX \`IDX_8b486b91e43537c87c4266053f\` ON \`business\``);
    await queryRunner.query(`DROP TABLE \`business\``);
    await queryRunner.query(`DROP INDEX \`REL_3f62b42ed23958b120c235f74d\` ON \`customer\``);
    await queryRunner.query(`DROP INDEX \`IDX_6c497e212bc2ac2329cb4c059d\` ON \`customer\``);
    await queryRunner.query(`DROP INDEX \`IDX_fdb2f3ad8115da4c7718109a6e\` ON \`customer\``);
    await queryRunner.query(`DROP INDEX \`IDX_47bd75ef7644513e402222cef7\` ON \`customer\``);
    await queryRunner.query(`DROP TABLE \`customer\``);
    await queryRunner.query(`DROP INDEX \`REL_ffad1a9aba53f8773fad14e2a3\` ON \`business_sales_report\``);
    await queryRunner.query(`DROP TABLE \`business_sales_report\``);
    await queryRunner.query(`DROP TABLE \`sales_report\``);
    await queryRunner.query(`DROP INDEX \`REL_51d41bcadff576b7477d729d56\` ON \`business_user\``);
    await queryRunner.query(`DROP INDEX \`IDX_2a95f576e13701ee12c7e502c4\` ON \`business_user\``);
    await queryRunner.query(`DROP INDEX \`IDX_f1f2813cda8ccf542ae045cc2d\` ON \`business_user\``);
    await queryRunner.query(`DROP TABLE \`business_user\``);
    await queryRunner.query(`DROP TABLE \`bank_account\``);
    await queryRunner.query(`DROP TABLE \`bank\``);
    await queryRunner.query(`DROP INDEX \`REL_9949557d0e1b2c19e5344c171e\` ON \`access_token\``);
    await queryRunner.query(`DROP TABLE \`access_token\``);
  }
}
